// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for projects documents */
interface ProjectsDocumentData {
    /**
     * sdadsa field in *projects*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.sdadsa
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    sdadsa: prismicT.RichTextField;
}
/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ProjectsDocumentData>, "projects", Lang>;
export type AllDocumentTypes = ProjectsDocument;
/**
 * Primary content in AlmoxarifadoAutomotiva → Primary
 *
 */
interface AlmoxarifadoAutomotivaSliceDefaultPrimary {
    /**
     * Title field in *AlmoxarifadoAutomotiva → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: almoxarifado_automotiva.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *AlmoxarifadoAutomotiva → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: almoxarifado_automotiva.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for AlmoxarifadoAutomotiva Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AlmoxarifadoAutomotiva`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AlmoxarifadoAutomotivaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AlmoxarifadoAutomotivaSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AlmoxarifadoAutomotiva*
 *
 */
type AlmoxarifadoAutomotivaSliceVariation = AlmoxarifadoAutomotivaSliceDefault;
/**
 * AlmoxarifadoAutomotiva Shared Slice
 *
 * - **API ID**: `almoxarifado_automotiva`
 * - **Description**: `AlmoxarifadoAutomotiva`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AlmoxarifadoAutomotivaSlice = prismicT.SharedSlice<"almoxarifado_automotiva", AlmoxarifadoAutomotivaSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ProjectsDocumentData, ProjectsDocument, AllDocumentTypes, AlmoxarifadoAutomotivaSliceDefaultPrimary, AlmoxarifadoAutomotivaSliceDefault, AlmoxarifadoAutomotivaSliceVariation, AlmoxarifadoAutomotivaSlice };
    }
}
