// Code generated by Slice Machine. DO NOT EDIT.

import AlmoxarifadoAutomotiva from './AlmoxarifadoAutomotiva';

export {
	AlmoxarifadoAutomotiva,
};

export const components = {
	almoxarifado_automotiva: AlmoxarifadoAutomotiva,
};
